const {Router} =require('express')
const {registerUser,cheackEmail,checkPassword,userDetails,logout,updateProfilePic,updateUser,searchUser,imageUpload,imageDelete}=require('../controller/userController')
const {createGroup,addMember,leftGroup}=require('../controller/groupChatController')
const router=Router()
router.post('/register',registerUser)
router.post('/email',cheackEmail)
router.post('/password',checkPassword)
router.get('/user',userDetails)
router.get('/logout',logout)
router.post('/update-user-profile',updateProfilePic)
router.patch('/update-user',updateUser)
router.post('/search-user',searchUser)
router.post('/image',imageUpload)
router.post('/image-delete',imageDelete)
router.post('/group',createGroup)
router.post('/group/member/:id',addMember)
router.delete('/group/member/:id',leftGroup)
module.exports=router