const mongoose=require('mongoose')

const OneToOneMessageSchema=new mongoose.Schema({
  chatId:{
    type:mongoose.Schema.ObjectId,
    required:true,
    ref:'OnetoOneChat'
  },
  sender:{
    type:mongoose.Schema.ObjectId,
    required:true,
    ref:'User'
  },
  receiver:{
    type:mongoose.Schema.ObjectId,
    required:true,
    ref:'User'
  },
  text:{
    type:String,
    default:""
  },
  imageUrl:{
    type:String,
    default:""
  },
  videoUrl:{
    type:String,
    default:""
  },
  sent:{
    type:Boolean,
    default:false
  },
  delivered:{
    type:Boolean,
    default:false
  },
  read:{
      type:Boolean,
      default:false
  },
  deletedForSender:{
      type:Boolean,
      default:false
  },
  deletedForReceiver:{
      type:Boolean,
      default:false
  },
},{
  timestamps:true
})

module.exports=mongoose.model('OneToOneMessage',OneToOneMessageSchema)